# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rohan Davenport
tagline:          'Rohan Davenport'
description:      'Google's design teams are crazy.<br>My school blog of tech and life.'
url:              http://d3sk.me/

author:
  name:           'Rohan Davenport'
  url:            http://d3sk.me/

paginate:         2

github:
  repo:           https://github.com/d3sk/d3sk.github.io



