# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rohan Davenport
tagline:          'Rohan Davenport'
description:      'Googles design team must be on crack.<br>My school blog of tech and life.'
url:              http://d3sk.me/

author:
  name:           'Rohan Davenport'
  url:            http://d3sk.me/

paginate:         2


gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/qian256/qian256.github.io/

tags:


